Return-Path: <userdev@example.com>
Received: from mail.example.com (LHLO mail.example.com) (172.10.10.100) by
 mail.example.com with LMTP; Mon, 13 May 2024 10:20:15 +0700 (ICT)
Received: from localhost (localhost.localdomain [127.0.0.1])
        by mail.example.com (Postfix) with ESMTP id 81919706DCF
        for <userit@example.com>; Mon, 13 May 2024 10:20:15 +0700 (+07)
X-Spam-Flag: NO
X-Spam-Score: -1.009
X-Spam-Level:
X-Spam-Status: No, score=-1.009 required=6.6 tests=[ALL_TRUSTED=-1,
 HTML_MESSAGE=0.001, T_SCC_BODY_TEXT_LINE=-0.01]
 autolearn=ham autolearn_force=no
Received: from mail.example.com ([127.0.0.1])
 by localhost (mail.example.com [127.0.0.1]) (amavis, port 10032) with ESMTP
 id 1k56Y6SgTE0B for <userit@example.com>;
 Mon, 13 May 2024 10:20:15 +0700 (+07)
Received: from localhost (localhost.localdomain [127.0.0.1])
        by mail.example.com (Postfix) with ESMTP id 5101D706DB5
        for <userit@example.com>; Mon, 13 May 2024 10:20:15 +0700 (+07)
X-Virus-Scanned: amavis at example.com
Received: from mail.example.com ([127.0.0.1])
 by localhost (mail.example.com [127.0.0.1]) (amavis, port 10026) with ESMTP
 id pYbB6F2yRMNS for <userit@example.com>;
 Mon, 13 May 2024 10:20:15 +0700 (+07)
Received: from mail.example.com (mail.example.com [172.10.10.100])
        by mail.example.com (Postfix) with ESMTP id 38059706DCF
        for <userit@example.com>; Mon, 13 May 2024 10:20:15 +0700 (+07)
Date: Mon, 13 May 2024 10:20:15 +0700 (ICT)
From: dev <userdev@example.com>
To: userit <userit@example.com>
Message-ID: <1119215671.263.1715570415207.JavaMail.zimbra@example.com>
Subject: Hi there
MIME-Version: 1.0
Content-Type: multipart/alternative;
        boundary="=_7919a7cb-4852-47ca-9734-03cf0b12eb9c"
X-Originating-IP: [172.10.10.100]
X-Mailer: Zimbra 10.0.7_GA_4598 (ZimbraModernWebClient - FF125 (Linux)/10.0.7_GA_4598)
Thread-Index: Msk1lmZyavp3nyewZS9/19ObPc22Vg==
Thread-Topic: Hi there

--=_7919a7cb-4852-47ca-9734-03cf0b12eb9c
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

Thank you for taking the time to answer my questions and I look forward to hearing from you.Sincerely,Derrick Smith
I had fun meeting you and designing our Career Focused Project together on Tuesday
I know we agreed that I would make a PowerPoint presentation

--=_7919a7cb-4852-47ca-9734-03cf0b12eb9c
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<html><body><div style="font-size: 12pt; font-family: arial, helvetica, sans-serif; color: #000000;" data-attr="forced_root_block_attrs">khong con gi de mat</div></body></html>
--=_7919a7cb-4852-47ca-9734-03cf0b12eb9c--